# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# A topology kind representing an Aether Enterprise node
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: fabric
spec:
  aspects: {}

# Fabrics as targets
{{- range .Values.fabrics }}
---
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: {{ .id }}
spec:
  uri: {{ .id }}
  kind:
    name: fabric
  aspects:
    onos.topo.Configurable:
      address: fabric-adapter-v0-1:5150
      version: 0.1.x
      type: sdn-fabric
    onos.topo.ControllerInfo:
      control_endpoint:
        address: {{ .onos.address }}
        port: {{ .onos.port }}
      username: {{ .onos.username }}
      password: {{ .onos.password }}
    onos.topo.Location:
      lat: {{ .lat }}
      lng: {{ .long }}
    onos.topo.TLSOptions:
      insecure: true
    onos.topo.Asset:
      name: {{ .name }}
    onos.topo.MastershipState: {}
{{- end }}
