# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: rasa-model-server
description: Rasa Model Server
kubeVersion: ">=1.15.0"
type: application
version: 0.0.4
appVersion: v0.0.13
keywords:
  - aether
  - exporter
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
