# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

nameOverride: ""
fullnameOverride: "rasa-model-server"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/chronos-exporter
  tag: v0.0.11
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP

modelfiles: /opt/rasa-models/
