# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: v2
name: config-model-plproxy
version: 1.0.0
kubeVersion: ">=1.18.0"
appVersion: 1.0.0
description: Prom label proxy config model
keywords:
  - plproxy
  - config
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
