# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: sdcore-adapter-v2-1
kubeVersion: ">=1.17.0"
type: application
version: 2.1.1
appVersion: v2.1.0
description: Aether SD-Core Adapter
keywords:
  - aether
  - sdcore
  - adapter
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
