# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: fabric-adapter
kubeVersion: ">=1.17.0"
type: application
version: 0.1.3
appVersion: v0.0.5
description: Aether Fabric Adapter
keywords:
  - aether
  - fabric
  - adapter
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Intel
    email: scott.baker@intel.com
