# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: {{ template "aether.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aether.labels" . | nindent 4 }}
spec:
  plugin:
    type: Aether
    version: {{ .Chart.AppVersion | quote }}
  modules:
  - name: onf-connectivity-service
    organization: Open Networking Foundation
    revision: 2022-01-14
    file: onf-connectivity-service.yang
  - name: onf-enterprise
    organization: Open Networking Foundation
    revision: 2022-01-14
    file: onf-enterprise.yang
  files:
    {{- range $path, $_  := $.Files.Glob "files/yang/*.yang" }}
    {{ base $path }}: |
{{ $.Files.Get $path | indent 6 }}
    {{- end }}
