# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: {{ template "plproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plproxy.labels" . | nindent 4 }}
spec:
  plugin:
    type: PLProxy
    version: {{ .Chart.AppVersion | quote }}
  modules:
  - name: plproxy-service
    organization: Open Networking Foundation
    revision: 2021-09-24
    file: prom-label-proxy.yang
  files:
    {{- range $path, $_  := $.Files.Glob "files/yang/*.yang" }}
    {{ base $path }}: |
{{ $.Files.Get $path | indent 6 }}
    {{- end }}
