# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: primitives.atomix.io/v2beta1
kind: Counter
metadata:
  name: fabric-adapter-sid-counter
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "fabric-adapter.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: fabric-adapter-sid-map
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "fabric-adapter.store.consensus.name" . }}
    {{- end }}
---