# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
enterprise:
  enterprise-id: tesla
  display-name: Tesla
  image: https://en.wikipedia.org/wiki/File:Tesla_Motors.svg
sites:
  - site-id: freemont
    display-name: Freemont, CA
    image: https://en.wikipedia.org/wiki/File:Mission_Peak_over_Lake_Elizabeth,_in_Fremont,_California_(cropped).JPG
    small-cells:
      - small-cell-id: freemont-sc-north
        display-name: North Cell
      - small-cell-id: freemont-sc-south
        display-name: South Cell
      - small-cell-id: freemont-sc-east
        display-name: East Cell
      - small-cell-id: freemont-sc-west
        display-name: West Cell
    slices:
      - slice-id: freemont-slice-cameras
        display-name: Cameras Slice
        device-groups:
          - cameras
        applications:
          - nvr-application
          - occupant-counter
      - slice-id: freemont-slice-phones
        display-name: Phones Slice
        device-groups:
          - phones
        applications:
          - expenses-application
    device-groups:
      - device-group-id: phones
        display-name: Phones group
        devices:
          - 752365A
          - 752908B
      - device-group-id: cameras
        display-name: Cameras group
        devices:
          - 7568111
          - 7568112
          - 7568113
          - 7568114
          - 7568115
          - 7568116
          - 7568117
    devices:
      - serial-number: 752365A
        imei: 123-456-7891
        display-name: Phone 1
        location: Somewhere
        type: Pixel 5 Phone
        sim: 123-456-789
      - serial-number: 752908B
        imei: 123-456-7892
        display-name: Phone 2
        location: Somewhere
        type: iPhone 11
        sim: 123-456-788
      - serial-number: 7568111
        imei: 123-456-7893
        display-name: Camera 1
        location: Front entrance
        type: Camera
        sim: 123-456-787
      - serial-number: 7568112
        imei: 123-456-7894
        display-name: Camera 2
        location: South Gate
        type: Camera
        sim: 123-456-786
      - serial-number: 7568113
        imei: 123-456-7895
        display-name: Camera 3
        location: Store Room 1
        type: Camera
        sim: 123-456-785
      - serial-number: 7568114
        imei: 123-456-7896
        display-name: Camera 4
        location: Store Room 2
        type: Camera
        sim: 123-456-784
      - serial-number: 7568115
        imei: 123-456-7897
        display-name: Camera 5
        location: Corridor 1
        type: Camera
        sim: 123-456-783
      - serial-number: 7568116
        imei: 123-456-7898
        display-name: Camera 6
        location: Corridor 2
        type: Camera
        sim: 123-456-782
      - serial-number: 7568117
        imei: 123-456-7899
        display-name: Camera 7
        location: Atrium
        type: Camera
        sim: 123-456-781
    sims:
      - iccid: 123-456-789
        display-name: Sim 9
      - iccid: 123-456-788
        display-name: Sim 8
      - iccid: 123-456-787
        display-name: Sim 7
      - iccid: 123-456-786
        display-name: Sim 6
      - iccid: 123-456-785
        display-name: Sim 5
      - iccid: 123-456-784
        display-name: Sim 4
      - iccid: 123-456-783
        display-name: Sim 3
      - iccid: 123-456-782
        display-name: Sim 2
      - iccid: 123-456-781
        display-name: Sim 1
  - site-id: berlin
    display-name: Berlin, DE
    image: https://en.wikipedia.org/wiki/Berlin#/media/File:Brandenburger_Tor_abends.jpg
    small-cells:
      - small-cell-id: berlin-sc-north
        display-name: North Cell
      - small-cell-id: berlin-sc-south
        display-name: South Cell
      - small-cell-id: berlin-sc-east
        display-name: East Cell
      - small-cell-id: berlin-sc-west
        display-name: West Cell
    slices:
      - slice-id: berlin-slice-cameras
        display-name: Cameras Slice
        device-groups:
          - cameras
        applications:
          - nvr-application
          - occupant-counter
      - slice-id: berlin-slice-phones
        display-name: Phones Slice
        device-groups:
          - phones
        applications:
          - expenses-application
    device-groups:
      - device-group-id: phones
        display-name: Phones group
        devices:
          - 18876871
          - 18876872
          - 18876873
          - 18876874
          - 18876875
      - device-group-id: cameras
        display-name: Cameras group
        devices:
          - 18876881
          - 18876882
          - 18876883
          - 18876884
          - 18876885
          - 18876886
          - 18876887
    devices:
      - serial-number: 18876871
        imei: 123-456-7891
        display-name: Phone 1
        location: Somewhere
        type: Pixel 5 Phone
        sim: 123-671-789
      - serial-number: 18876872
        imei: 123-671-7892
        display-name: Phone 2
        location: Somewhere
        type: iPhone 11
        sim: 123-671-788
      - serial-number: 18876873
        imei: 123-671-7893
        display-name: Phone 3
        location: Somewhere
        type: iPhone 11
        sim: 123-671-787
      - serial-number: 18876874
        imei: 123-671-7894
        display-name: Phone 4
        location: Somewhere
        type: iPhone 11
        sim: 123-671-786
      - serial-number: 18876875
        imei: 123-671-7895
        display-name: Phone 5
        location: Somewhere
        type: iPhone 11
        sim: 123-671-785
      - serial-number: 18876881
        imei: 123-671-7896
        display-name: Camera 1
        location: Front entrance
        type: Camera
        sim: 123-671-784
      - serial-number: 18876882
        imei: 123-671-7897
        display-name: Camera 2
        location: South Gate
        type: Camera
        sim: 123-671-783
      - serial-number: 18876883
        imei: 123-671-7898
        display-name: Camera 3
        location: Store Room 1
        type: Camera
        sim: 123-671-782
      - serial-number: 18876884
        imei: 123-671-7899
        display-name: Camera 4
        location: Store Room 2
        type: Camera
        sim: 123-671-781
      - serial-number: 18876885
        imei: 123-671-7900
        display-name: Camera 5
        location: Corridor 1
        type: Camera
        sim: 123-671-780
      - serial-number: 18876886
        imei: 123-671-7901
        display-name: Camera 6
        location: Corridor 2
        type: Camera
        sim: 123-671-779
      - serial-number: 18876887
        imei: 123-671-7902
        display-name: Camera 7
        location: Atrium
        type: Camera
        sim: 123-671-778
    sims:
      - iccid: 123-671-789
        display-name: Sim 9
      - iccid: 123-671-788
        display-name: Sim 8
      - iccid: 123-671-787
        display-name: Sim 7
      - iccid: 123-671-786
        display-name: Sim 6
      - iccid: 123-671-785
        display-name: Sim 5
      - iccid: 123-671-784
        display-name: Sim 4
      - iccid: 123-671-783
        display-name: Sim 3
      - iccid: 123-671-782
        display-name: Sim 2
      - iccid: 123-671-781
        display-name: Sim 1
      - iccid: 123-671-780
        display-name: Sim 1a
      - iccid: 123-671-779
        display-name: Sim 1b
      - iccid: 123-671-778
        display-name: Sim 1c
applications:
  - application-id: nvr-application
    display-name: Network Video Recorder
  - application-id: occupant-counter
    display-name: Occupant Counting Application
  - application-id: expenses-application
    display-name: Expenses Application
